services:
  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/armada_db
    volumes:
      - ./src:/usr/src/app/src
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: